### ISSUE TITLE
saveat doesn't work when specifying a negative part of tspan

### ISSUE THREAD

**Issue by macd** [JuliaDiffEq/BoundaryValueDiffEq.jl#3]
When solving a BVP over [-1, 1] (ie tspan = (-1.0, 1.0) )  and specifying a saveat=0.01, only the values of x (ie t) over 0.0 are stored.  This can be seen in the following script drop.jl.  This is with the development version of BoundaryValueDiffEq and the following version of Julia:

    Version 0.7.0-DEV.66 (2017-05-08 17:16 UTC)
    Commit 25f241c* (2 days old master)

### drop.jl
# MATLAB Guide, Higham and Higham example on p. 214 (Third Edition)
using BoundaryValueDiffEq
using DiffEqBase, OrdinaryDiffEq
using PyPlot

function drop_d!(x, y, dy)
    dy[1] = y[2]
    dy[2] = (y[1] - 1) * ((1 + y[2]^2)^(3/2))
end

function bc!(resid, sol)
  resid[1] = sol[1][1]
  resid[2] = sol[end][1]
end

# this will show the problem
tspan = (-1.0, 1.0)

# use the following and it works
#tspan = (0.0, 2.0)

u0 = [0., 1.]
bvp = BVProblem(drop_d!, bc!, u0, tspan)
resid_f = Array(Float64, 2)

sol = solve(bvp, Shooting(Tsit5()))
bc!(resid_f, sol)
println("Norm of residual: ", norm(resid_f))

sol2 = solve(bvp, Shooting(Tsit5()), saveat=0.01)
bc!(resid_f, sol2)
println("Norm of residual: ", norm(resid_f))

plot(sol.t, sol[1, :], label="No saveat")
plot(sol2.t, sol2[1, :], "*", label="Using saveat")
legend()
title("Water droplet BVP solved by BVProblem")
axis("equal")

**Comment by ChrisRackauckas** [comment]
Fixed on OrdinaryDiffEq.jl master. This was actually a problem with saveat there... yikes... thank you for catching this! 

Note that `Shooting` should be fully functional (as you see here), but this library is definitely a work-in-progress. Feel free to start using it if you want to and file bug reports, but it won't be documented until it's closer to complete. I'm actually quite surprised someone found this already!

**Comment by macd** [comment]
Cool!  Many thanks.
