### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/BoundaryValueDiffEq.jl#45]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEq

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEq

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by oscardssmith** [comment]
@JuliaRegistrator register()

**Comment by oscardssmith** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ErikQQY** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register() subdir=lib/BoundaryValueDiffEqAscher

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqCore

Release notes:

## Breaking changes

- Verbosity now uses SciMLLogging.jl

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqCore

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqAscher

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqMIRKN

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqShooting

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqMIRK

**Comment by ErikQQY** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqFIRK

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqCore

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqShooting

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/BoundaryValueDiffEqMIRK
